### ISSUE TITLE
Supplying an email address fails

### ISSUE THREAD

**Issue by guystreeter** [maksimstojkovic/docker-letsencrypt#1]
On line 17 of `cert.sh`, quoting the `${EMAIL_PARAM}` string causes all of `-m <supplied.address> --no-eff-email` to be passed to `certbot` as a single parameter, when it should be three. This causes `certbot` to prompt for an email address, which fails.

Quoting the expanded value is not necessary. I have tested without it.

**Comment by maksimstojkovic** [comment]
Hi,
I have just tested it and was able to replicate the issue.

```
There seem to be problems with that address. Enter email address (used for
urgent renewal and security notices)


If you really want to skip this, you can run the client with
--register-unsafely-without-email but you will then be unable to receive notice
about impending expiration or revocation of your certificates or problems with
your Certbot installation that will lead to failure to renew.

 (Enter 'c' to cancel): An unexpected error occurred:
EOFError
Please see the logfiles in /var/log/letsencrypt for more details.
ERROR: Failed to create SSL certificates
```

This was one of the first docker images I created so there may be a few bugs in it 😅.
It will be updated shortly.

**Comment by maksimstojkovic** [comment]
Hi @guystreeter,

The issue should now be fixed.
I have also added `UID` and `GID` environment variables which update ownership of Let's Encrypt files within the container.
