### ISSUE TITLE
Subdomains 

### ISSUE THREAD

**Issue by tamimology** [maksimstojkovic/docker-letsencrypt#4]
Is it possible to have ssl for the domain and subdomains as well?

From the wildcard option it is either this or that, can you add a boolean option to have for both, i.e
Domain: domain.duckdns.org
Wildcard : true
Subdomains_included: true

By this the ssl will be for the domain.duckdns.org and all *.domain.duckdns.org as well.

**Comment by maksimstojkovic** [comment]
Hi @tamimology,

This is currently a limitation of certbot `dns` verification. Consequently the resulting SSL certificate can only cover either a main domain, OR all subdomains, but not both simultaneously. As far as I am aware, there aren't any known workarounds for this specific issue, but if you do come across one, please reopen this issue so I can work on implementing the feature.
