### ISSUE TITLE
Adding --preferred-chain variable to the script

### ISSUE THREAD

**Issue by dumdedumda** [maksimstojkovic/docker-letsencrypt#5]
"DST Root CA X3" certificate from Let's Encrypt expired in September of 2021, but the script still seems to be pulling DST Root CA certificates. Any plans to incorporate "--preferred-chain" environment variable to Certbot to the docker script soon so it can pull ISRG Root X1 certs?

**Comment by maksimstojkovic** [comment]
Hi @dumdedumda,
This should now be fixed. Support for `--preferred-chain` has been added.
Additionally, the latest rebuild should now use the correct certificate chains by default.
If there are any further issue, please reopen this thread.
